version: '3.8'

services:

  backend:
    build: ./zakupy
    command: sh startup.sh
    volumes:
      - ./zakupy:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_URL=${POSTGRES_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_URL}:5432/${POSTGRES_DB}
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.4
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
