version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /pb/zakupyBackend serve --http=0.0.0.0:8000
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - 8000:8000
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
