"""unique product + table rename

Revision ID: 3388ee5c42e3
Revises: 9af40f99d3e0
Create Date: 2023-02-22 18:16:36.079075

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy



# revision identifiers, used by Alembic.
revision = '3388ee5c42e3'
down_revision = '9af40f99d3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product')
    )
    op.drop_table('shoppinglist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppinglist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shoppinglist_pkey')
    )
    op.drop_table('shopping_list')
    # ### end Alembic commands ###
