"""add source category relationship

Revision ID: 5e125c9f9ae2
Revises: d099d48f179d
Create Date: 2023-03-16 18:24:49.647800

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import fastapi_users_db_sqlalchemy



# revision identifiers, used by Alembic.
revision = '5e125c9f9ae2'
down_revision = 'd099d48f179d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('product_list', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('product_list', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_list', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product_list', 'sources', ['source_id'], ['id'])
    op.drop_column('product_list', 'category')
    op.drop_column('product_list', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_list', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product_list', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_list', type_='foreignkey')
    op.drop_constraint(None, 'product_list', type_='foreignkey')
    op.drop_column('product_list', 'category_id')
    op.drop_column('product_list', 'source_id')
    op.drop_table('sources')
    op.drop_table('categories')
    # ### end Alembic commands ###
