name: Upload Go test results

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get -v ./...
      - name: Build
        run: go build -o zakupyBackend -a pkg/main.go
        env:
          ADMIN_EMAIL: ${{ secrets.DOCKER_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Upload Go binary
        uses: actions/upload-artifact@v3
        with:
          name: zakupyBackend
          path: zakupyBackend
